import React from 'react';

function Shop() {
  return <div className='shop'>

       <ul className='shop__list'>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
       </ul>
       <ul className='shop__list'>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
           <li className="shop__list-li">div</li>
       </ul>
  </div>;
}

export default Shop;
